text = input("Enter a string: ")

print("Original String:", text)
print("Length:", len(text))
print("Upper Case:", text.upper())
print("Lower Case:", text.lower())
print("strip:", text.strip())
print("Split:", text.split())
print("find 'ar':",text.find ('ar'))
print("concatination:",text + "usha")
print("repetation:",text*3)
print("index:",text[4])
print("slice:",text[1:4])
print("membership:","karthika" in text)
print("membership:","raji" in text)
print("replace:",text.replace("karthika","divij"))
print("count:",text.count('r'))
print("startswith usha:",text.strip().startswith("usha"))
print("endswith ka:",text.strip().endswith("ka"))